### ISSUE TITLE
[proposal] YAML to include description per language

### ISSUE THREAD

**Issue by nishad** [cyriac/afterfloodinfographics#4]
Existing 'Kerala Floods Info Social Share Content' sheet has separate description for each language, so it is better if we restructure the YAML assuming there is no separate tag sets per language.

Something like, 

```yaml
# After Flood Infographics 
---
# Metadata for YAML, this can be expanded later

# A simple ISO 8601 timestamp possibly with Time
# This will be handy to identify if the YAML is up-to-date 
timestamp : 2018-09-04T15:00

# List of projects inside a project key,
# This will help us to expand the scope and structure of YAML without altering codes
projects :     # Projects as lists of dictionaries 
  - id: '17.5' # Project ID
    title: Helpline numbers for snake rescuers and helpline # Project Title
    languages: # All released language sets as dictionary
      english: # Individual Languages
        description: Sample description
               # Description per language
        pdf: https://drive.google.com/open?id=1Mga6UswWtQ-XtXrjbh6s4vCGt3WBZS5z
               # PDF URL
        png:   # PNG URL(s) as list
          - https://drive.google.com/open?id=1AjDvlFImePPnxJI09c-cdTVmdzo2Pubx
          - https://drive.google.com/open?id=1AjDvlFImePPnxJI09c-cdTVmdzo2Pubx
    tags:      # Tags per project in English
      - tag 1 
      - tag 2
      - tag 3
...
```
